#!/bin/sh
ln -sf ~/dotfiles/.vimrc ~/.vimrc
ln -sf ~/dotfiles/.vim/autoload ~/.vim/autoload
ln -sf ~/dotfiles/.vim/colors ~/.vim/colors
ln -sf ~/dotfiles/.bash_profile ~/.bash_profile
ln -sf ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/.tmuxinator ~/.tmuxinator
ln -sf ~/dotfiles/.zshrc ~/.zshrc
ln -sf ~/dotfiles/.ctags ~/.ctags
ln -sf ~/dotfiles/.ctags ~/.ctags.d/configure.ctags
ln -sf ~/dotfiles/.editorconfig ~/.editorconfig
ln -sf ~/dotfiles/atom/keymap.cson ~/.atom/keymap.cson
ln -sf ~/dotfiles/atom/config.cson ~/.atom/config.cson
ln -sf ~/dotfiles/karabiner.json ~/.config/karabiner/karabiner.json
ln -sf ~/dotfiles/.gitconfig ~/.gitconfig
ln -sf ~/dotfiles/.stCommitMsg ~/.stCommitMsg
ln -sf ~/dotfiles/.gitignore_global ~/.gitignore_global
ln -sf ~/dotfiles/.agignore ~/.agignore
ln -sf ~/dotfiles/.tigrc ~/.tigrc
ln -sf ~/dotfiles/.php_cs.dist ~/.php_cs.dist
ln -sf ~/dotfiles/config.fish ~/.config/fish/config.fish
ln -sf ~/dotfiles/nvim/init.vim ~/.config/nvim/init.vim
ln -sf ~/dotfiles/nvim/plugins.toml ~/.config/nvim/plugins.toml
ln -sf ~/dotfiles/nvim/coc-settings.json ~/.config/nvim/coc-settings.json
ln -sf ~/dotfiles/nvim/sonictemplate ~/.config/nvim/sonictemplate
ln -sf ~/dotfiles/plugins.sbt ~/.sbt/1.0/plugins/plugins.sbt
ln -sf ~/dotfiles/global.sbt ~/.sbt/1.0/plugins/global.sbt
