[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim")'

[[plugins]]
repo  = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'kana/vim-altr'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'janko-m/vim-test'
depends = ['vim-dispatch']
hook_add = '''
let g:test#strategy = 'dispatch'
'''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'tyru/operator-camelize.vim'

[[plugins]]
repo = 'bkad/CamelCaseMotion'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'kamykn/spelunker.vim'

[[plugins]]
repo = 'mattn/vim-sonictemplate'

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'

[[plugins]]
repo = 'neovim/node-host'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']
build = './install.sh'

[[plugins]]
repo = 'styled-components/vim-styled-components'
on_ft = ['javascript', 'typescript', 'javascript.jsx', 'typescript.tsx']

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'php', 'javascript', 'javascript.jsx', 'jsx', 'typescript', 'typescript.tsx', 'tsx', 'vue', 'javascript.vue', 'typescript.vue']

[[plugins]]
repo = 'AndrewRadev/tagalong.vim'
on_ft = ['html', 'php', 'javascript', 'javascript.jsx', 'jsx', 'typescript', 'typescript.tsx', 'tsx', 'vue', 'javascript.vue', 'typescript.vue']

[[plugins]]
repo = 'gko/vim-coloresque'
on_ft = ['html', 'css', 'scss', 'php', 'javascript', 'javascript.jsx', 'jsx', 'typescript', 'typescript.tsx', 'tsx', 'vue', 'javascript.vue', 'typescript.vue']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['scss']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
on_i = 1

[[plugins]]
repo = 'gabrielelana/vim-markdown'
on_ft = ['markdown','mkd']

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = 'graphql'

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['markdown']
'''

[[plugins]]
repo = 'glacambre/firenvim'
hook_post_update = '''
  call firenvim#install(0)
'''
