[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1
if = 'has("nvim")'

[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo  = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'kana/vim-altr'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'janko-m/vim-test'
depends = ['vim-dispatch']
hook_add = '''
let g:test#strategy = 'dispatch'
'''

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'twitvim/twitVim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'kamykn/spelunker.vim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'
build = 'make'

[[plugins]]
repo = 'landaire/deoplete-swift'
on_ft = 'swift'

[[plugins]]
repo ='carlitux/deoplete-ternjs'
on_ft = ['javascript', 'typescript']
build = 'npm install -g tern'

[[plugins]]
repo = 'Galooshi/vim-import-js'
on_ft = ['javascript']

[[plugins]]
repo = 'neovim/node-host'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']
hook_post_update = '''
  let g:dein#plugin.build = 'npm install'
'''

[[plugins]]
repo = 'billyvg/tigris.nvim'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']
hook_post_update = '''
  let g:dein#plugin.build = './install.sh'
'''

[[plugins]]
repo = 'styled-components/vim-styled-components'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']
build = 'make -f make_mac.mak'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue', 'javascript', 'javascript.vue']

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'php', 'javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
on_i = 1

[[plugins]]
repo = 'gabrielelana/vim-markdown'
on_ft = ['markdown','mkd']

[[plugins]]
repo = 'kballard/vim-swift'
on_ft = 'swift'

[[plugins]]
repo = 'keith/swift.vim'
on_ft = 'swift'

[[plugins]]
repo = 'lvht/phpcd.vim'
on_ft = 'php'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = 'graphql'
