[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1
if = 'has("nvim")'

[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'kana/vim-altr'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo  = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'
build = 'make'

[[plugins]]
repo = 'Galooshi/vim-import-js'
on_ft = ['javascript']

repo = 'neovim/node-host'
on_ft = ['javascript']
hook_post_update = '''
  let g:dein#plugin.build = 'npm install'
'''

[[plugins]]
repo = 'billyvg/tigris.nvim'
on_ft = ['javascript']
hook_post_update = '''
  let g:dein#plugin.build = './install.sh'
'''

[[plugins]]
repo ='carlitux/deoplete-ternjs'
on_ft = ['javascript']
build = 'npm install -g tern'

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['javascript', 'html']

[[plugins]]
repo = 'styled-components/vim-styled-components'
on_ft = ['javascript']

[[plugins]]
repo = 'stephpy/vim-php-cs-fixer'
on_ft = 'php'

[[plugins]]
repo = 'sbdchd/neoformat'

[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
on_i = 1

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'gabrielelana/vim-markdown'
on_ft = ['markdown','mkd']
