# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"
apply = ["defer"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[templates]
defer = ""

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.prezto]
github = "sorin-ionescu/prezto"
use = ["init.zsh"]
apply = ["source"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.base16]
github = "chriskempson/base16-shell"

[plugins.kubectl-completion]
remote = "https://raw.githubusercontent.com/nnao45/zsh-kubectl-completion/master/_kubectl"
apply = ["fpath"]

[plugins.git-completion]
remote = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh"
apply = ["fpath"]

[plugins.git-completion-bash]
remote = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
apply = ["fpath"]

[plugins.git-prompt]
remote = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
apply = ["source"]

[plugins.zsh-better-npm-completion]
github = "lukechilds/zsh-better-npm-completion"

[plugins.bun]
remote = "https://raw.githubusercontent.com/oven-sh/bun/6d52b3b62b6ba1171ba97bd9509f7e8e8611624f/completions/bun.zsh"
apply = ["source"]

# [plugins.autojump]
# github = "wting/autojump"
# dir = "bin"
# apply = ["PATH", "source"]
